### PR TITLE
Use PEP-517 build system

### LINKED ISSUE #8: `_generated/ffi.py` missing from binary install
Hi,

I just noticed this:

```
$ echo $VIRTUAL_ENV
/tmp/toto
$ pip install -U pangocairocffi
Processing /root/.cache/pip/wheels/5e/b4/90/3317813d0940443f4e9302caf89a8b7fe79eaf174823abadea/pangocairocffi-0.3.0-py3-none-any.whl
Requirement already satisfied, skipping upgrade: cairocffi>=1.0.2 in /tmp/toto/lib/python3.8/site-packages (from pangocairocffi) (1.1.0)
Requirement already satisfied, skipping upgrade: cffi>=1.1.0 in /tmp/toto/lib/python3.8/site-packages (from pangocairocffi) (1.14.3)
Requirement already satisfied, skipping upgrade: pangocffi>=0.4.0 in /tmp/toto/lib/python3.8/site-packages (from pangocairocffi) (0.6.0)
Requirement already satisfied, skipping upgrade: setuptools>=39.2.0 in /tmp/toto/lib/python3.8/site-packages (from cairocffi>=1.0.2->pangocairocffi) (50.3.0)
Requirement already satisfied, skipping upgrade: pycparser in /tmp/toto/lib/python3.8/site-packages (from cffi>=1.1.0->pangocairocffi) (2.20)
Installing collected packages: pangocairocffi
Successfully installed pangocairocffi-0.3.0
```

but then 
```
$ ls -al /tmp/toto/lib/python3.8/site-packages/pangocairocffi/_generated/
drwxr-xr-x 3 root root 4096 Sep 23 10:13 .
drwxr-xr-x 4 root root 4096 Sep 23 10:13 ..
drwxr-xr-x 2 root root 4096 Sep 23 10:13 __pycache__
-rw-r--r-- 1 root root   47 Sep 23 10:13 ffi_pango.py
```

While if I do
```
$ pip install --no-binary :all: -U pangocairocffi
Collecting pangocairocffi
  Using cached pangocairocffi-0.3.0.tar.gz (20 kB)
Requirement already satisfied, skipping upgrade: cffi>=1.1.0 in /tmp/toto/lib/python3.8/site-packages (from pangocairocffi) (1.14.3)
Requirement already satisfied, skipping upgrade: cairocffi>=1.0.2 in /tmp/toto/lib/python3.8/site-packages (from pangocairocffi) (1.1.0)
Requirement already satisfied, skipping upgrade: pangocffi>=0.4.0 in /tmp/toto/lib/python3.8/site-packages (from pangocairocffi) (0.6.0)
Requirement already satisfied, skipping upgrade: pycparser in /tmp/toto/lib/python3.8/site-packages (from cffi>=1.1.0->pangocairocffi) (2.20)
Requirement already satisfied, skipping upgrade: setuptools>=39.2.0 in /tmp/toto/lib/python3.8/site-packages (from cairocffi>=1.0.2->pangocairocffi) (50.3.0)
Skipping wheel build for pangocairocffi, due to binaries being disabled for it.
Installing collected packages: pangocairocffi
    Running setup.py install for pangocairocffi ... done
Successfully installed pangocairocffi-0.3.0

$ ls -al /tmp/toto/lib/python3.8/site-packages/pangocairocffi/_generated/
drwxr-xr-x 3 root root  4096 Sep 23 10:16 .
drwxr-xr-x 4 root root  4096 Sep 23 10:16 ..
drwxr-xr-x 2 root root  4096 Sep 23 10:16 __pycache__
-rw-r--r-- 1 root root 29120 Sep 23 10:16 ffi.py
-rw-r--r-- 1 root root    47 Mar 23  2019 ffi_pango.py
```

So the file `ffi.py` is properly set up, while it does not seem to be part of the binary archive. Taking a deeper look, when `wheel` is installed and upon first installation, the generated `whl` file in the cache does not contain the `ffi.py` file neither. Any subsequent installation in a virtual environment will have the same issue.

### PR DESCRIPTION
**Pull request by naveen521kk**
I think it fixes #8 
I exactly can't test it because I couldn't upload it to TestPyPI. Maybe after uploading it I can test. But I tried using git installs
```sh
pip install git+https://github.com/naveen521kk/pangocairocffi.git@fix-build#egg=pangocairocffi
```
and it seemed to work on creating a venv also. But this needs to be checked can you try it on testpypi @leifgehrmann.

### CODE REVIEW

**Comment by naveen521kk** [comment]
Looks like this solves the issue. I had a simple index on [gh-pages](https://naveen521kk.github.io/python-package-server/) and trying I couldn't reproduce #8 . Could anyone else check it?

**Comment by leifgehrmann** [comment]
Hi, thanks for looking into this more!

I've tried running the following in a clean environment:

```
# Clear the environment caches
rm -rf ~/.cache/pip
rm -rf ./venv

# Create virtual env
python3 -m venv venv

# Install
pip install cffi pangocffi git+https://github.com/naveen521kk/pangocairocffi.git@fix-build#egg=pangocairocffi
```

And this happens:

**Shell output:**
<details>

```
Collecting cffi
  Downloading cffi-1.14.3-cp38-cp38-manylinux1_x86_64.whl (410 kB)
     |████████████████████████████████| 410 kB 1.9 MB/s 
Collecting pangocffi
  Downloading pangocffi-0.7.0.tar.gz (33 kB)
Collecting pangocairocffi
  Cloning https://github.com/naveen521kk/pangocairocffi.git (to revision fix-build) to /tmp/pip-install-1mksrp12/pangocairocffi
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/user/Documents/pangocairocffi-test/venv/bin/python3 /home/user/Documents/pangocairocffi-test/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp1fm4_3i3
         cwd: /tmp/pip-install-1mksrp12/pangocairocffi
    Complete output (38 lines):
    Traceback (most recent call last):
      File "/home/user/Documents/pangocairocffi-test/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/home/user/Documents/pangocairocffi-test/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/user/Documents/pangocairocffi-test/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-4uotkui_/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-4uotkui_/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 253, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/tmp/pip-build-env-4uotkui_/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 9, in <module>
        setup(
      File "/tmp/pip-build-env-4uotkui_/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-4uotkui_/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 423, in __init__
        _Distribution.__init__(self, {
      File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-4uotkui_/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 695, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-4uotkui_/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 702, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-4uotkui_/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-build-env-4uotkui_/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-build-env-4uotkui_/overlay/lib/python3.8/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "pangocairocffi/ffi_build.py", line 11, in <module>
        from pangocffi.ffi_instance_builder import \
      File "/tmp/pip-build-env-4uotkui_/overlay/lib/python3.8/site-packages/pangocffi/__init__.py", line 2, in <module>
        from ._generated.ffi import ffi
    ModuleNotFoundError: No module named 'pangocffi._generated'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/user/Documents/pangocairocffi-test/venv/bin/python3 /home/user/Documents/pangocairocffi-test/venv/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp1fm4_3i3 Check the logs for full command output.
```

</details>

Can you confirm that this doesn't happen when you run the command above?

Note, it's important that one does the `python install` in a one-liner.

I know that if one splits out the install into 3 different lines, pangocairocffi install successfully (See the output below). But unfortunately, pip doesn't install dependencies like this, probably because of how it resolves dependency management.

**Shell output:**
<details>

```
$ pip install cffi
Collecting cffi
  Downloading cffi-1.14.3-cp38-cp38-manylinux1_x86_64.whl (410 kB)
     |████████████████████████████████| 410 kB 2.0 MB/s 
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 5.3 MB/s 
Installing collected packages: pycparser, cffi
Successfully installed cffi-1.14.3 pycparser-2.20
$
$ pip install pangocffi
Collecting pangocffi
  Downloading pangocffi-0.7.0.tar.gz (33 kB)
Requirement already satisfied: cffi>=1.1.0 in ./venv/lib/python3.8/site-packages (from pangocffi) (1.14.3)
Requirement already satisfied: pycparser in ./venv/lib/python3.8/site-packages (from cffi>=1.1.0->pangocffi) (2.20)
Building wheels for collected packages: pangocffi
  Building wheel for pangocffi (setup.py) ... done
  Created wheel for pangocffi: filename=pangocffi-0.7.0-py3-none-any.whl size=48498 sha256=9b1bc1b3b22f234c1108861e04f7356b5ce5c84eb57421cef32f6fc9751d70da
  Stored in directory: /home/user/.cache/pip/wheels/0d/3a/e0/b67e293764f644c1528ab042c477a7492340ca5183a4a01f11
Successfully built pangocffi
Installing collected packages: pangocffi
Successfully installed pangocffi-0.7.0
$
$ pip install git+https://github.com/naveen521kk/pangocairocffi.git@fix-build#egg=pangocairocffi
Collecting pangocairocffi
  Cloning https://github.com/naveen521kk/pangocairocffi.git (to revision fix-build) to /tmp/pip-install-ajz8uu5r/pangocairocffi
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting cairocffi>=1.0.2
  Downloading cairocffi-1.1.0.tar.gz (68 kB)
     |████████████████████████████████| 68 kB 1.5 MB/s 
Requirement already satisfied: pangocffi>=0.4.0 in ./venv/lib/python3.8/site-packages (from pangocairocffi) (0.7.0)
Requirement already satisfied: cffi>=1.1.0 in ./venv/lib/python3.8/site-packages (from pangocairocffi) (1.14.3)
Requirement already satisfied: setuptools>=39.2.0 in ./venv/lib/python3.8/site-packages (from cairocffi>=1.0.2->pangocairocffi) (44.0.0)
Requirement already satisfied: pycparser in ./venv/lib/python3.8/site-packages (from cffi>=1.1.0->pangocairocffi) (2.20)
Building wheels for collected packages: pangocairocffi, cairocffi
  Building wheel for pangocairocffi (PEP 517) ... done
  Created wheel for pangocairocffi: filename=pangocairocffi-0.3.2-py3-none-any.whl size=24032 sha256=5250cf43c703dbd35058a8f2e7de09025051d1074053e444be47d0bb59bfae9d
  Stored in directory: /tmp/pip-ephem-wheel-cache-53fffnnc/wheels/9f/5f/5a/ab95efc9f7886a24fd07b344e2d9a20630a7170f2c59b92c4d
  Building wheel for cairocffi (setup.py) ... done
  Created wheel for cairocffi: filename=cairocffi-1.1.0-py3-none-any.whl size=88586 sha256=7ebb552c3ab8c739d6b753c26672d9759a66a90fb5cd5ac7f0b1cd034268d698
  Stored in directory: /home/user/.cache/pip/wheels/71/c7/16/0cd3bf6e08dae3bd2edeb3e731447c4864559f55bc1a15f7e1
Successfully built pangocairocffi cairocffi
Installing collected packages: cairocffi, pangocairocffi
Successfully installed cairocffi-1.1.0 pangocairocffi-0.3.2
```

</details>

----

Meanwhile, after doing a bit of research on how cairocffi works (Thanks for the suggestion in #13 btw), I've noticed that cairocffi has a dependency on a library [xcffib](https://github.com/tych0/xcffib).

This is interesting because, just like pangocairocffi has a dependency on pangocffi and both of which do C-FFI building, cairocffi and xcffib are both C-FFI building packages as well.

In xcffib, in their [`__init__.py` file](https://github.com/tych0/xcffib/blob/master/module/__init__.py), they have the following line:

```
try:
    from xcffib._ffi import ffi
except ImportError:
    from xcffib.ffi_build import ffi
```

Where as pangocffi's [`__init__.py` file](https://github.com/leifgehrmann/pangocffi/blob/master/pangocffi/__init__.py) does not have the try-except:

```
from ._generated.ffi import ffi
```

It appears xcffib falls back to running `ffi_build.py` if the generated file doesn't exist even after installing.

So, my plan is to do something similar in pangocffi, though I need to be careful with testing this properly...

I hope to try this out tomorrow when I have time.

**Comment by naveen521kk** [comment]
Ok, I don't know how to fix that. If you know you could try out.

It tries to get metadata from setuptools before actually installing any dependency but finds itself in a place to run setup.py and it fails.

**Comment by naveen521kk** [comment]
I don't think this PR is necessary.

**Pull request closed without merging**
